config/routes.rb
Rails.application.routes.draw do

  post 'update_form' => 'posts#update_form'
  delete 'destroy_photo/:id' => 'posts#destroy_photo', as: :destroy_photo
  get '/search_suggestions' => 'public#search_suggestions', as: :search_suggestions
  get '/search' => 'public#search', as: :search
  post 'login' => 'session#create', as: :login
  get 'logout' => 'session#destroy', as: :logout
  get 'login' => 'session#new'
  get 'stats' => 'admin#stats', as: :stats

  resources :posts   
  get ':action' => 'public#action'
  mount Attachinary::Engine => "/attachinary"
  root 'public#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base

	include PgSearch
  	pg_search_scope :search, 
		  					against: [[:title, 'A'],[:desc, 'B']], 
			  				:using => {
			                  :tsearch => {:prefix => true}
			                }


	validate :validate_travel_pin
	belongs_to :category
	has_attachments :photos, maximum: 30


	default_scope { order(created_at: :desc) }
	
	scope :travel, -> { where(category_id: 1).includes(:photo_files)}
	scope :food, -> { where(category_id: 2).includes(:photo_files)}
	scope :life, -> { where(category_id: 3).includes(:photo_files)}


	validates_presence_of :title, :desc, :category_id
	validates :desc, length: { minimum: 10}
	validates :title, length: { minimum: 3}


	def self.paginate_it (params)
		paginate(page: params, per_page: 4).includes(:photo_files)
	end

	def validate_travel_pin
		 if (self.category_id == 1 && (self.locX == nil || self.locY == nil))
		 	errors.add(:location, "is not set")  
		 	false
		 end
	end
	def self.search_suggestions(term)
	  where('LOWER(title) LIKE :term', term: "%#{term.downcase}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	helper_method :current_user

	def authenticate_user
		redirect_to login_path  if current_user.nil?
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:update, :destroy]
  before_action :find_post_with_photos, only: [:show, :edit]
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	if @post.save
  		redirect_to @post, notice: 'Post added successfully'
  	else
  		flash.now.notice = 'Some errors occured, cannot create post.'
  		render :new
  	end
  end

  def show

  end
  def edit
  end

  def update
  	if @post.update(post_params)
      if @post.category_id == 4 
        redirect_to '/about', notice: 'About me updated successfully'
      else
  		  redirect_to @post, notice: 'Post updated successfully'
      end
  	else
  		flash.now.notice = 'Some errors occured, cannot update post.'
  		render :edit
  	end
  end

  def destroy
  	if @post.destroy
  		redirect_to :root, notice: 'Post deleted successfully'
  	else
  		redirect_to @post, notice: 'Cannot delete post, some errors occured'
  	end
  end
  def update_form
    @category_id = params[:category_id]

    respond_to do |format|
      format.js
    end
  end

  def destroy_photo
    @photo = Photo.find(params[:id])
    
    if @photo.destroy
      respond_to do |format|
        format.js
      end
    else
      render :edit, notice: 'Cannot destroy photo'
    end
  end



private
	def find_post
		@post = Post.find(params[:id])
	end
  def find_post_with_photos
    @post = Post.includes(:photo_files).find(params[:id])
  end
	def post_params
		params.require(:post).permit(:title,:desc,:category_id, :locX, :locY, photos: [])
	end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  rescue_from ActionView::MissingTemplate do
    render :index
  end

  def index
  	@posts = Post.where.not(id: 1).paginate_it(params[:page])
  end

  def travels
  	@posts = Post.travel.paginate_it(params[:page])
    @pins = Post.travel.pluck(:locX, :locY, :id, :title, :created_at)
    @controller = 'travels'
  end

  def food
  	@posts = Post.food.paginate_it(params[:page])
    @controller = 'food'
  end

  def life
  	@posts = Post.life.paginate_it(params[:page])
    @controller = 'life'
  end

  def about
  	@post = Post.includes(:photo_files).find_by(id: 1)
    render :nothing unless @post
  end
  
  def search
    @controller = 'search'
    if params[:search].present? 
      @posts = Post.paginate_it(params[:page]).search(params[:search]) 
      p
    else
      redirect_to action: :index
    end
  end

  def search_suggestions
    render json: Post.search(params[:term]).limit(3).pluck(:title)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
		redirect_to :root if current_user
	end

	def create
		reset_session
		user = User.find_by(login: params[:login])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to :root
		else
			flash.now.notice = 'Invalid login or password'
			render :new
		end
	end

	def destroy
		reset_session
		redirect_to :root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
	def post_cat_name cat_id
		case cat_id
			when 1
				'travels'
			when 2
				'food'
			when 3
				'life'
			when 4
				'about'
		end	
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.haml
%html
	%head
		%title Blog
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		%link{:href => "https://fonts.googleapis.com/css?family=Raleway:200|Roboto:100,300", :rel => "stylesheet", :type => "text/css"}/
		= csrf_meta_tags
		= cloudinary_js_config 
	%body
		%header
			.container
				#top_menu
					%nav
						=link_to :root do
							#logo_image
						%ul
							= link_to '/life' do
								%li= 'my life'
							|
							= link_to '/travels' do
								%li= 'travels'
							|
							= link_to '/food' do
								%li= 'food'
							|
							= link_to '/about' do
								%li= 'about me'
						
					-if current_user
						.admin
							=link_to '+ Add post', new_post_path, class: 'button add_post'
							=link_to 'Statistics', stats_path, class: 'button stats'
							=link_to 'Logout', logout_path, class: 'button logout'
					- else
						.search
							= form_tag search_path, method: :get do
								= text_field_tag :search,'', id: 'search'
								= submit_tag 'Search'
					/ - else
					/ 	.social
					/ 		=link_to 'https://www.facebook.com/dominika.jagiela?fref=ts' do
					/ 			=image_tag 'fb-icon.png'	
					/ 		=link_to 'gmail' do
					/ 			=image_tag 'gmail-icon.png'	
			#logo_banner
				.banner_text
					.smaller
						= 'OPEN THE DOOR'
						%br/
					.smaller_more
						= 'TO MY'
						%br/
					.bigger
						= 'DREAMS'
	- if flash[:notice]
		#notice
			= flash[:notice]
	= yield

			

app/views/posts/_form.html.haml
=form_for @post, html: {multipart: true, id: 'new_post'} do |f|
	-if @post.errors.any?
		%ul.errors
			- @post.errors.full_messages.each do |msg|
				%li= msg	

	.input
		= f.label :category_id
		= f.select :category_id, [['travels', 1], ['food', 2], ['my life', 3], ['about', 4]], prompt: '- select category -'
	.input
		= f.label :title
		= f.text_field :title
	.input
		= f.label :desc, 'Content'
		= f.text_area :desc, class: "tinymce"
	.upload
		= 'Drag & drop or click to add photos'
		= f.attachinary_file_field :photos
	.clear
	.submit
		= f.submit
		
	= f.number_field :locX, type: 'hidden'
	= f.number_field :locY, type: 'hidden'
	

app/views/posts/_post.html.haml
.post.sample{class: post_cat_name(post.category_id)}
	%header.sample= post.title
	%footer.sample= post.created_at.strftime('%d/%m/%Y')
	%article.samlpe_art= truncate_html post.desc, length: 300
	-if post.photos.any?	
		.photos.mini
			-post.photos.each_with_index do |photo, i|
				- break if i == 4
				= link_to (cloudinary_url photo.path), data: {lightbox: 'example-set'} do
					= cl_image_tag photo.path, size: '200x100', crop: :fill
			.clear
	= link_to post do
		.button.edit= 'read more...'
	- if current_user
		= link_to edit_post_path(post) do
			.button.edit edit
	.clear.shadow

app/views/posts/edit.html.haml
#map_form
	#refresh_pin_button Resetuj flage
	#map_photo
		= image_tag 'map.jpg'
		
.container
	= render 'form'

app/views/posts/new.html.haml
#map_form
	#refresh_pin_button Resetuj flage
	#map_photo
		= image_tag 'map.jpg'
		
.container
	= render 'form'

app/views/posts/show.html.haml
.container
	%section
		.post
			%header= @post.title
			%footer= @post.created_at.strftime('%d/%m/%Y')
			%article= @post.desc.html_safe
			- if @post.category_id == 1
				#roll_map
					#map_photo
						= image_tag 'map.jpg'
						.map_pin#location_pin{style: "left: #{@post.locX}%; top: #{@post.locY}%"}
			-if @post.photos	
				.photos
					-@post.photos.each do |photo|
						= link_to (cloudinary_url photo.path), data: {lightbox: 'example-set'} do
							= cl_image_tag photo.path, size: '240x130', crop: :fill
					.clear

			= link_to :back do
				.button.edit back
			- if current_user
				= link_to edit_post_path(@post) do
					.button.edit edit
				= link_to @post, method: 'delete', data: {confirm: 'Are you sure?'} do
					.button.edit destroy

		

app/views/posts/update_form.js.erb
refresh_pin = function() {
  $('#location_pin').remove();
  $('#map_photo').off('click');
  set_pin();
  $('#refresh_pin_button').fadeOut();
};

set_pin = function() {
  map = $('#map_photo');
  map.css('cursor', 'url(<%= asset_path "flag.png" %>), auto');
  map.on('click', function(e) {

    offset = $(this).offset();
    left_offset = ((e.pageX - offset.left) / $(this).width()) * 100;
    top_offset = ((e.pageY - offset.top) / $(this).height()) * 100;
    add_pin(left_offset, top_offset);
    map.off('click');
    map.css('cursor', 'auto');
    $('#refresh_pin_button').fadeIn()
  });
};

add_pin = function(x, y) {
  map = $('#map_photo');
	$('<div>').addClass('map_pin').attr('id', 'location_pin').css({
	  'left': x + '%',
	  'top': y + '%'
	}).appendTo('#map_photo');
  $('#post_locX').val(x);
  $('#post_locY').val(y);
};



<% if @category_id.to_i == 1 %>
  $('#refresh_pin_button').hide();
	$('#map_form').slideDown();

	set_pin();
	$('#refresh_pin_button').click(function(e) {
   	refresh_pin();
  });
<% else %>
	$('#map_form').slideUp();
<% end %>

app/views/session/new.html.haml
.container_mini
	=form_tag login_path, id: 'login_form' do
		.input
			= label_tag :login
			= text_field_tag :login, '', autofocus: true
		.input
			= label_tag :password
			= password_field_tag :password, '',autocomplete: 'off'
		.submit
			= submit_tag 'Log in'